/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_TYPES_H
#define protocol_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace similarity {

typedef std::vector<class ReplyEntry>  ReplyEntryList;

class ReplyEntry;

class QueryException;

typedef struct _ReplyEntry__isset {
  _ReplyEntry__isset() : externId(false), obj(false) {}
  bool externId :1;
  bool obj :1;
} _ReplyEntry__isset;

class ReplyEntry {
 public:

  static const char* ascii_fingerprint; // = "88CBA07510E178963213D17442259E4C";
  static const uint8_t binary_fingerprint[16]; // = {0x88,0xCB,0xA0,0x75,0x10,0xE1,0x78,0x96,0x32,0x13,0xD1,0x74,0x42,0x25,0x9E,0x4C};

  ReplyEntry(const ReplyEntry&);
  ReplyEntry& operator=(const ReplyEntry&);
  ReplyEntry() : id(0), dist(0), externId(), obj() {
  }

  virtual ~ReplyEntry() throw();
  int32_t id;
  double dist;
  std::string externId;
  std::string obj;

  _ReplyEntry__isset __isset;

  void __set_id(const int32_t val);

  void __set_dist(const double val);

  void __set_externId(const std::string& val);

  void __set_obj(const std::string& val);

  bool operator == (const ReplyEntry & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(dist == rhs.dist))
      return false;
    if (__isset.externId != rhs.__isset.externId)
      return false;
    else if (__isset.externId && !(externId == rhs.externId))
      return false;
    if (__isset.obj != rhs.__isset.obj)
      return false;
    else if (__isset.obj && !(obj == rhs.obj))
      return false;
    return true;
  }
  bool operator != (const ReplyEntry &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReplyEntry & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ReplyEntry& obj);
};

void swap(ReplyEntry &a, ReplyEntry &b);

typedef struct _QueryException__isset {
  _QueryException__isset() : message(false) {}
  bool message :1;
} _QueryException__isset;

class QueryException : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  QueryException(const QueryException&);
  QueryException& operator=(const QueryException&);
  QueryException() : message() {
  }

  virtual ~QueryException() throw();
  std::string message;

  _QueryException__isset __isset;

  void __set_message(const std::string& val);

  bool operator == (const QueryException & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const QueryException &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const QueryException & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const QueryException& obj);
};

void swap(QueryException &a, QueryException &b);

} // namespace

#endif
