/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_constants.h"

namespace similarity {

const protocolConstants g_protocol_constants;

protocolConstants::protocolConstants() {
}

} // namespace

