/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.cmu.lti.oaqa.similarity;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-6")
public class ReplyEntry implements org.apache.thrift.TBase<ReplyEntry, ReplyEntry._Fields>, java.io.Serializable, Cloneable, Comparable<ReplyEntry> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReplyEntry");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DIST_FIELD_DESC = new org.apache.thrift.protocol.TField("dist", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField EXTERN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("externId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField OBJ_FIELD_DESC = new org.apache.thrift.protocol.TField("obj", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReplyEntryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReplyEntryTupleSchemeFactory());
  }

  public int id; // required
  public double dist; // required
  public String externId; // optional
  public String obj; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    DIST((short)2, "dist"),
    EXTERN_ID((short)3, "externId"),
    OBJ((short)4, "obj");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // DIST
          return DIST;
        case 3: // EXTERN_ID
          return EXTERN_ID;
        case 4: // OBJ
          return OBJ;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __DIST_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.EXTERN_ID,_Fields.OBJ};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DIST, new org.apache.thrift.meta_data.FieldMetaData("dist", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.EXTERN_ID, new org.apache.thrift.meta_data.FieldMetaData("externId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OBJ, new org.apache.thrift.meta_data.FieldMetaData("obj", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReplyEntry.class, metaDataMap);
  }

  public ReplyEntry() {
  }

  public ReplyEntry(
    int id,
    double dist)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.dist = dist;
    setDistIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReplyEntry(ReplyEntry other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.dist = other.dist;
    if (other.isSetExternId()) {
      this.externId = other.externId;
    }
    if (other.isSetObj()) {
      this.obj = other.obj;
    }
  }

  public ReplyEntry deepCopy() {
    return new ReplyEntry(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setDistIsSet(false);
    this.dist = 0.0;
    this.externId = null;
    this.obj = null;
  }

  public int getId() {
    return this.id;
  }

  public ReplyEntry setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public double getDist() {
    return this.dist;
  }

  public ReplyEntry setDist(double dist) {
    this.dist = dist;
    setDistIsSet(true);
    return this;
  }

  public void unsetDist() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DIST_ISSET_ID);
  }

  /** Returns true if field dist is set (has been assigned a value) and false otherwise */
  public boolean isSetDist() {
    return EncodingUtils.testBit(__isset_bitfield, __DIST_ISSET_ID);
  }

  public void setDistIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DIST_ISSET_ID, value);
  }

  public String getExternId() {
    return this.externId;
  }

  public ReplyEntry setExternId(String externId) {
    this.externId = externId;
    return this;
  }

  public void unsetExternId() {
    this.externId = null;
  }

  /** Returns true if field externId is set (has been assigned a value) and false otherwise */
  public boolean isSetExternId() {
    return this.externId != null;
  }

  public void setExternIdIsSet(boolean value) {
    if (!value) {
      this.externId = null;
    }
  }

  public String getObj() {
    return this.obj;
  }

  public ReplyEntry setObj(String obj) {
    this.obj = obj;
    return this;
  }

  public void unsetObj() {
    this.obj = null;
  }

  /** Returns true if field obj is set (has been assigned a value) and false otherwise */
  public boolean isSetObj() {
    return this.obj != null;
  }

  public void setObjIsSet(boolean value) {
    if (!value) {
      this.obj = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Integer)value);
      }
      break;

    case DIST:
      if (value == null) {
        unsetDist();
      } else {
        setDist((Double)value);
      }
      break;

    case EXTERN_ID:
      if (value == null) {
        unsetExternId();
      } else {
        setExternId((String)value);
      }
      break;

    case OBJ:
      if (value == null) {
        unsetObj();
      } else {
        setObj((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Integer.valueOf(getId());

    case DIST:
      return Double.valueOf(getDist());

    case EXTERN_ID:
      return getExternId();

    case OBJ:
      return getObj();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case DIST:
      return isSetDist();
    case EXTERN_ID:
      return isSetExternId();
    case OBJ:
      return isSetObj();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReplyEntry)
      return this.equals((ReplyEntry)that);
    return false;
  }

  public boolean equals(ReplyEntry that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_dist = true;
    boolean that_present_dist = true;
    if (this_present_dist || that_present_dist) {
      if (!(this_present_dist && that_present_dist))
        return false;
      if (this.dist != that.dist)
        return false;
    }

    boolean this_present_externId = true && this.isSetExternId();
    boolean that_present_externId = true && that.isSetExternId();
    if (this_present_externId || that_present_externId) {
      if (!(this_present_externId && that_present_externId))
        return false;
      if (!this.externId.equals(that.externId))
        return false;
    }

    boolean this_present_obj = true && this.isSetObj();
    boolean that_present_obj = true && that.isSetObj();
    if (this_present_obj || that_present_obj) {
      if (!(this_present_obj && that_present_obj))
        return false;
      if (!this.obj.equals(that.obj))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_id = true;
    list.add(present_id);
    if (present_id)
      list.add(id);

    boolean present_dist = true;
    list.add(present_dist);
    if (present_dist)
      list.add(dist);

    boolean present_externId = true && (isSetExternId());
    list.add(present_externId);
    if (present_externId)
      list.add(externId);

    boolean present_obj = true && (isSetObj());
    list.add(present_obj);
    if (present_obj)
      list.add(obj);

    return list.hashCode();
  }

  @Override
  public int compareTo(ReplyEntry other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDist()).compareTo(other.isSetDist());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDist()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dist, other.dist);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExternId()).compareTo(other.isSetExternId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExternId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.externId, other.externId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetObj()).compareTo(other.isSetObj());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetObj()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.obj, other.obj);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReplyEntry(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("dist:");
    sb.append(this.dist);
    first = false;
    if (isSetExternId()) {
      if (!first) sb.append(", ");
      sb.append("externId:");
      if (this.externId == null) {
        sb.append("null");
      } else {
        sb.append(this.externId);
      }
      first = false;
    }
    if (isSetObj()) {
      if (!first) sb.append(", ");
      sb.append("obj:");
      if (this.obj == null) {
        sb.append("null");
      } else {
        sb.append(this.obj);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'id' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'dist' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReplyEntryStandardSchemeFactory implements SchemeFactory {
    public ReplyEntryStandardScheme getScheme() {
      return new ReplyEntryStandardScheme();
    }
  }

  private static class ReplyEntryStandardScheme extends StandardScheme<ReplyEntry> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReplyEntry struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DIST
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.dist = iprot.readDouble();
              struct.setDistIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXTERN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.externId = iprot.readString();
              struct.setExternIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OBJ
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.obj = iprot.readString();
              struct.setObjIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetDist()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'dist' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReplyEntry struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(DIST_FIELD_DESC);
      oprot.writeDouble(struct.dist);
      oprot.writeFieldEnd();
      if (struct.externId != null) {
        if (struct.isSetExternId()) {
          oprot.writeFieldBegin(EXTERN_ID_FIELD_DESC);
          oprot.writeString(struct.externId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.obj != null) {
        if (struct.isSetObj()) {
          oprot.writeFieldBegin(OBJ_FIELD_DESC);
          oprot.writeString(struct.obj);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReplyEntryTupleSchemeFactory implements SchemeFactory {
    public ReplyEntryTupleScheme getScheme() {
      return new ReplyEntryTupleScheme();
    }
  }

  private static class ReplyEntryTupleScheme extends TupleScheme<ReplyEntry> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReplyEntry struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.id);
      oprot.writeDouble(struct.dist);
      BitSet optionals = new BitSet();
      if (struct.isSetExternId()) {
        optionals.set(0);
      }
      if (struct.isSetObj()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetExternId()) {
        oprot.writeString(struct.externId);
      }
      if (struct.isSetObj()) {
        oprot.writeString(struct.obj);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReplyEntry struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.id = iprot.readI32();
      struct.setIdIsSet(true);
      struct.dist = iprot.readDouble();
      struct.setDistIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.externId = iprot.readString();
        struct.setExternIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.obj = iprot.readString();
        struct.setObjIsSet(true);
      }
    }
  }

}

