/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace similarity {


ReplyEntry::~ReplyEntry() throw() {
}


void ReplyEntry::__set_id(const std::string& val) {
  this->id = val;
}

void ReplyEntry::__set_dist(const double val) {
  this->dist = val;
}

void ReplyEntry::__set_obj(const std::string& val) {
  this->obj = val;
__isset.obj = true;
}

const char* ReplyEntry::ascii_fingerprint = "CAD99879040BB94BCA63533B6094F391";
const uint8_t ReplyEntry::binary_fingerprint[16] = {0xCA,0xD9,0x98,0x79,0x04,0x0B,0xB9,0x4B,0xCA,0x63,0x53,0x3B,0x60,0x94,0xF3,0x91};

uint32_t ReplyEntry::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_id = false;
  bool isset_dist = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->id);
          isset_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->dist);
          isset_dist = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->obj);
          this->__isset.obj = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_dist)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t ReplyEntry::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("ReplyEntry");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("dist", ::apache::thrift::protocol::T_DOUBLE, 2);
  xfer += oprot->writeDouble(this->dist);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.obj) {
    xfer += oprot->writeFieldBegin("obj", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->obj);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(ReplyEntry &a, ReplyEntry &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.dist, b.dist);
  swap(a.obj, b.obj);
  swap(a.__isset, b.__isset);
}

ReplyEntry::ReplyEntry(const ReplyEntry& other0) {
  id = other0.id;
  dist = other0.dist;
  obj = other0.obj;
  __isset = other0.__isset;
}
ReplyEntry& ReplyEntry::operator=(const ReplyEntry& other1) {
  id = other1.id;
  dist = other1.dist;
  obj = other1.obj;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const ReplyEntry& obj) {
  using apache::thrift::to_string;
  out << "ReplyEntry(";
  out << "id=" << to_string(obj.id);
  out << ", " << "dist=" << to_string(obj.dist);
  out << ", " << "obj="; (obj.__isset.obj ? (out << to_string(obj.obj)) : (out << "<null>"));
  out << ")";
  return out;
}


QueryException::~QueryException() throw() {
}


void QueryException::__set_message(const std::string& val) {
  this->message = val;
}

const char* QueryException::ascii_fingerprint = "EFB929595D312AC8F305D5A794CFEDA1";
const uint8_t QueryException::binary_fingerprint[16] = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

uint32_t QueryException::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->message);
          this->__isset.message = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t QueryException::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("QueryException");

  xfer += oprot->writeFieldBegin("message", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->message);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(QueryException &a, QueryException &b) {
  using ::std::swap;
  swap(a.message, b.message);
  swap(a.__isset, b.__isset);
}

QueryException::QueryException(const QueryException& other2) : TException() {
  message = other2.message;
  __isset = other2.__isset;
}
QueryException& QueryException::operator=(const QueryException& other3) {
  message = other3.message;
  __isset = other3.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const QueryException& obj) {
  using apache::thrift::to_string;
  out << "QueryException(";
  out << "message=" << to_string(obj.message);
  out << ")";
  return out;
}

} // namespace
