/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_CONSTANTS_H
#define protocol_CONSTANTS_H

#include "protocol_types.h"

namespace similarity {

class protocolConstants {
 public:
  protocolConstants();

};

extern const protocolConstants g_protocol_constants;

} // namespace

#endif
